dist: trusty
sudo: false

language: node_js
node_js:
  - '12'

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - npm run build

after_success:
  - bash <(curl -s https://codecov.io/bash)